version: '3'
services:
  node1:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data/node1:/data
    command: --port 8080

  node2:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - ./data/node2:/data
    command: --port 8080 --peers node1:8080

  node3:
    build: .
    ports:
      - "8082:8080"
    volumes:
      - ./data/node3:/data
    command: --port 8080 --peers node1:8080,node2:8080 