version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: sphere_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sphere
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
